Enhance dot_bashrc.tmpl with new 'newapp' function for creating React apps, add 'bup' alias for bashrc reloading, and conditionally set 'cat' alias to 'batcat'. Introduce dot_inputrc for improved command completion settings. Update packages.toml to include 'bat'.

diff --git a/home/dot_bashrc.tmpl b/home/dot_bashrc.tmpl
--- a/home/dot_bashrc.tmpl
+++ b/home/dot_bashrc.tmpl
@@ -29,6 +29,11 @@ alias doc='lazydocker'
 eval "$(starship init bash)"
 {{- end }}
 
+{{- if lookPath "batcat" }}
+alias cat=batcat
+{{- end}}
+
+{{/* end non Omarchy: */}}
 {{- end }}
 
 {{/* Homebrew */}}
@@ -41,6 +46,7 @@ eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
 
 # Aliases
 alias dot=chezmoi
+alias bup="dot apply && source ~/.bashrc"
 alias s='jq ".scripts" package.json'
 alias p='pnpm'
 alias rmr='rm -rf --one-file-system --preserve-root'
@@ -61,6 +67,29 @@ function y() {
 
 mcd() {
   mkdir -p "$1" && cd "$1"
+}
+
+newapp() {
+  if [[ -z "$1" ]]; then
+    echo "Usage: newapp <app-name>"
+    return 1
+  fi
+
+  local app_name="$1"
+  if pnpx create-react-router@latest "$app_name" \
+    --git-init \
+    --install \
+    --package-manager pnpm \
+    --yes \
+    --template stianthaulow/rr-template \
+    --show-install-output false \
+    >/dev/null
+  then
+    cd "$app_name"
+  else
+    echo "create-react-router failed" >&2
+    return 1
+  fi
 }
 
 # Edit bash profile
